name: GitHub Actions Demo
run-name: ${{ github.actor }} is checking system against assessment image
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull and run given Docker image
        run: |
          docker pull mrksdh/assessment
          docker run -d -p 8080:8080 --name assessment mrksdh/assessment

      - name: Wait for assessment-container to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/v1/dataset; then
              echo "Assessment container is ready!"
              break
            fi
            echo "Waiting for assessment container..."
            sleep 3
          done

      - name: Build local Dockerfile and run container
        run: |
          docker build -t my-local-container -f Dockerfile .
          docker run -d --name local-container --link assessment-container my-local-container

      - name: Wait for containers to be ready
        run: sleep 10  # Optional: Wartezeit von 10 Sekunden, um sicherzustellen, dass die Container bereit sind

      - name: Check Logs for assessment-container
        run: |
          echo "Logs from assessment:"
          docker logs assessment | tee assessment_logs.txt  # Protokolliere die Logs in eine Datei

      - name: Check Logs for local-container
        run: |
          echo "Logs from local-container:"
          docker logs local-container | tee local_logs.txt  # Protokolliere die Logs in eine Datei

      - name: Verify success in logs
        run: |
          # Überprüfe, ob die Erfolgsmeldung in den assessment-Logs vorhanden ist
          if grep -q '"code":200,"message":"well done!"' assessment_logs.txt; then
              echo "Erfolg: Die Nachricht 'well done!' wurde gefunden!"
          else
              echo "Fehler: Die Nachricht 'well done!' wurde nicht gefunden!"
              exit 1
          fi

      - name: Verify containers are running
        run: docker ps

      - name: Cleanup
        run: |
          docker stop assessment-container local-container
          docker rm assessment-container local-container
