      - name: GET request to Assessment Service
        id: get_data
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" http://localhost:8080/v1/dataset)
          echo "Response Code: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error fetching data!"
            exit 1
          fi
          echo "Response data:"
          cat response.json  # Optional: Output the response data

      - name: Output response.json for debugging
        run: |
          echo "Contents of response.json:"
          cat response.json

      - name: Prepare and send POST request
        run: |
          # Extract necessary information from the response
          CONSUMPTION_RESULT=$(jq '
            {result: [
              .events[] | 
              {customerId: .customerId, 
               consumption: if .eventType == "stop" then (.timestamp - (.events[] | select(.eventType == "start" and .workloadId == .workloadId).timestamp)) else 0 end}
            ]} | group_by(.customerId) | map({customerId: .[0].customerId, consumption: map(.consumption) | add})
          ' response.json)

          # Send the POST request
          POST_RESPONSE=$(curl -X POST http://localhost:8080/v1/result -H "Content-Type: application/json" -d "$CONSUMPTION_RESULT")
          echo "Response from POST request: $POST_RESPONSE"


