name: GitHub Actions Demo
run-name: ${{ github.actor }} is checking system against assessment image
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run using Docker Compose
        run: |
          docker-compose up --build -d  # Im Hintergrund ausführen

      - name: Send POST request to assessment container and display response
        run: |
          RESPONSE=$(curl -X POST http://assessment:8080/v1/result -H "Content-Type: application/json" -d '{"key": "value"}')
          echo "Response from POST request: $RESPONSE"

      - name: Verify containers are running
        run: |
          docker ps
